go test sudo: required

services:
  - docker

env:
  - DOCKER_BIND_LOCALHOST=true GO15VENDOREXPERIMENT=1

language: go

go:
  - 1.5
  - 1.6

install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover
  # - go get github.com/golang/lint/golint

script:
  - go vet -x $(go list ./... | grep -v /vendor/)
  - gotestcover -coverprofile="cover.out" -race -covermode="count" $(go list ./... | grep -v /vendor/)
  - goveralls -coverprofile="cover.out"
